project:
  type: website
  resources:
    - data
    - assets

execute:
  freeze: auto
website:
  site-url: https://ConnorB.github.io
  favicon: assets/images/favicon.ico
  twitter-card: true
  open-graph: true
  google-analytics: "G-ELB0F4QNPS"
  # Navbar with social links
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
  # Footer with same social links
  page-footer:
    left: |
      © 2025 Connor Brown
    right:
      - icon: github
        href: https://github.com/ConnorB
      - icon: mastodon
        href: https://mastodon.world/@connorbrown
      - icon: instagram
        href: https://instagram.com/conbro_
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/connorbrown.bsky.social
      - icon: twitter
        href: https://twitter.com/eco_conn
      - text: "{{< fa brands google-scholar >}}"
        href: https://scholar.google.com/citations?user=ppjBxFEAAAAJ&hl=en
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0002-9680-8930
format:
  html:
    theme: darkly
    css: styles.css   # optional, if you want custom CSS
    toc: true
    include-in-header: 
      - text: |
            <!-- Default Statcounter code for Github https://connorb.github.io/ -->
            <script type="text/javascript">
            var sc_project=13170590; 
            var sc_invisible=1; 
            var sc_security="a68567e2"; 
            </script>
            <script type="text/javascript"
            src="https://www.statcounter.com/counter/counter.js" async></script>
            <noscript><div class="statcounter"><a title="Web Analytics"
            href="https://statcounter.com/" target="_blank"><img class="statcounter"
            src="https://c.statcounter.com/13170590/0/a68567e2/1/" alt="Web Analytics"
            referrerPolicy="no-referrer-when-downgrade"></a></div></noscript>
            <!-- End of Statcounter Code -->
            